services:
  mysql8:
    container_name: reservation
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: jetbill123
      MYSQL_DATABASE: booking-restaurant
    volumes:
      - mysql_r_data:/var/lib/mysql
volumes:
  mysql_r_data: